### PR TITLE
initial stab at setting up CCI

### PR DESCRIPTION
**Pull request by irmiller22**
## Background

Moving jsonmatch repo from travisCI to CCI.

### CODE REVIEW

**Comment by bcen** [comment]
once this merge, will update my PR to use cci with py3.

**Comment by shermany** [comment]
@lra Can you check percolate's github to see why I keep getting subscribed to percolate's new repos? I'm no longer part of the organization as far as I can tell on my side.

**Comment by lra** [comment]
@shermany no idea, you are definitely not in it. You might want to check with github?

**Comment by shermany** [comment]
@lapointexavier @lra OK - Thanks for looking. Sorry to bother.

**Pull request merged**
